spring.application.name=SpringAI-Project
spring.ai.openai.api-key=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
spring.ai.openai.chat.model=gpt-3.5-turbo