spring.application.name=SpringAI-Project
spring.ai.openai.api-key=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
spring.ai.openai.chat.model=gpt-3.5-turbo